version: '3.8'

services:
  nginx-app:
    container_name: nginx-app
    image: nginx
    ports:
      - 8080:80
    labels:
      collect_logs: "true"
      job: "app"

networks:
  external:
    name: logging-example