{
 "title": "Fluentd",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "container",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   {
    "name": "job",
    "label": "job",
    "query": {}
   },
   {
    "name": "log_stream",
    "label": "stream",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total  Count of logs - app",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({tag_name=\"app\"} |= `` [$__interval]))"
    }
   ]
  },
  {
   "title": "Total  Count of logs - infra",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({tag_name=\"infra\"} |= `` [$__interval]))"
    }
   ]
  },
  {
   "title": "$container_name logs in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({container=~\"$container_name\"} [$__interval])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 1 },
   "options": {
    "content": "📊 Dashboard created by Sarah Mai (hope you like it!)\n"
   }
  },
  {
   "title": "Live logs with searchable_pattern - $searchable_pattern - in $container_name",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{container=~\"$container_name\"} |~ `(?i)$searchable_pattern`"
    }
   ]
  },
  {
   "title": "Total Count of live logs",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range and container",
   "gridPos": { "h": 8, "w": 3, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=~\"$container_name\"} |~ `(?i)$searchable_pattern` [$__interval]))"
    }
   ]
  },
  {
   "title": "$log_stream historical",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(container) (count_over_time({stream=\"$log_stream\", container=~\"$container_name\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Total count of $log_stream",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (count_over_time({stream=\"$log_stream\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Total count of log_stream in container \"$container_name\"",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(stream) (count_over_time({container=~\"$container_name\"} [$__range]))"
    }
   ]
  },
  { "title": "nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Nginx status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(code) (count_over_time({container=\"/nginx-app\"} | logfmt | remote != ``[1m]))"
    }
   ]
  },
  {
   "title": "Visitor IPs",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(remote) (count_over_time({container=\"/nginx-app\", stream=\"stdout\"} | logfmt | remote != `` [$__range]))"
    }
   ]
  },
  {
   "title": "Nginx status code",
   "type": "logs",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "{container=\"/nginx-app\", stream=\"stdout\"} |logfmt | json | line_format `{{.remote}} ➡️ {{.method}} on Path '{{.path}}' and HTTP status: {{.code}}`"
    }
   ]
  }
 ]
}