version: "3.7"

# set env variable COMPOSE_PROJECT_NAME and
# label com.docker.compose.project
name: loki-promtail

services:
  loki:
    container_name: loki
    image: grafana/loki:2.6.1
    ports:
      - "3100"
    command: -config.file=/etc/loki/local-config.yaml
    labels:
      logging: "promtail"
      job: "management"
    networks:
      - network

  promtail:
    container_name: promtail
    image: grafana/promtail:2.6.1
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"
    labels:
      logging: "promtail"
      job: "management"
    volumes:
      # custom config will read logs from the containers of this project
      - ./promtail/config/promtail-config.yaml:/etc/promtail/config.yml
      # to read container labels and logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network

  # will be available at http://127.0.0.1:3000
  # default credentials: admin/admin
  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.2
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-piechart-panel
    labels:
      logging: "promtail"
      job: "management"
    volumes:
      # automatically configure the loki datasource
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - network

networks:
  network:
    driver: bridge
    name: logging-example