version: "3.8"

# set env variable COMPOSE_PROJECT_NAME and
# label com.docker.compose.project
name: loki-promtail

services:
  loki:
    container_name: loki
    image: grafana/loki:2.6.1
    ports:
      - "3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - network
    labels:
      collect_logs: "true"
      job: "infra"

  logstash:
    container_name: logstash
    image: grafana/logstash-output-loki
    networks:
      - network
    ports:
      - '5044:5044'
    volumes:
      - type: bind
        source: ./logstash/config/logstash.conf
        target: /usr/share/logstash/pipeline
    environment:
      - XPACK_MONITORING_ENABLED=false
    labels:
      collect_logs: "true"
      job: "infra"

  # will be available at http://127.0.0.1:3000
  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.2
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-piechart-panel
    volumes:
      # automatically configure the loki datasource
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - network
    labels:
      collect_logs: "true"
      job: "infra"

networks:
  network:
    driver: bridge
    name: logging-example
