version: '3.8'

services:
  nginx-app:
    container_name: nginx-app
    image: nginx
    ports:
      - 8080:80
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224

networks:
  external:
    name: logging-example