version: '3.8'

services:
  fluentd:
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      xpack.license.self_generated.type: basic
      xpack.security.enabled: false
    expose:
      - "9200"
    ports:
      - "9200:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    networks:
      - network
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: infra

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - kibanadata:/usr/share/kibana/data
    networks:
      - network
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: infra

volumes:
  esdata01:
      driver: local
      driver_opts:
        type: none
        device: /data/elastic
        o: bind
  kibanadata:
      driver: local
      driver_opts:
        type: none
        device: /data/kibana
        o: bind

networks:
  network:
    driver: bridge
    name: logging-example
