version: '3.8'

services:
  nginx-app:
    container_name: nginx-app
    image: nginx
    labels:
      logging: "promtail"
      job: "app"
    ports:
      - 8080:80
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: app

networks:
    external:
      name: logging-example